home:
  path: /{_locale}
  defaults:  { _controller: 'controller.home:indexAction', _locale: en }
  requirements:
      _locale:  en|fr|es

searchCountry:
  path: /searchCountry
  defaults: { _controller: 'controller.api.searchCountry:indexAction' }
  methods: POST

searchFlies:
  path: /{_locale}/searchFlies
  defaults: { _controller: 'controller.api.searchFlies:indexAction', _locale: en }
  requirements:
      _locale:  en|fr|es
  methods: POST

searchTickets:
  path: /searchTickets
  defaults: { _controller: 'controller.api.searchTickets:indexAction' }
  methods: POST
