home:
  path: /
  defaults: { _controller: 'controller.home:indexAction' }

searchCountry:
  path: /searchCountry
  defaults: { _controller: 'controller.api.searchCountry:indexAction' }
  methods: POST

searchFlies:
  path: /searchFlies
  defaults: { _controller: 'controller.api.searchFlies:indexAction' }
  methods: POST

searchTickets:
  path: /searchTickets
  defaults: { _controller: 'controller.api.searchTickets:indexAction' }
  methods: POST
